[package]
name = "rustpy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pyo3 = "0.20.0"
dyse_rust = {path = "../dyse_rust"}

[lib]
name = "socks"
path = "src/lib.rs"
